"""
Channel-specific response formatters.
Every outbound message passes through format_for_channel() before delivery.
"""

_WHATSAPP_MAX = 300


def format_for_channel(response: str, channel: str, ticket_id: str = "") -> str:
    """Format a raw agent response for the target channel."""
    if channel == "email":
        return _format_email(response, ticket_id)
    if channel == "whatsapp":
        return _format_whatsapp(response)
    return _format_web_form(response)   # web_form default


def _format_email(response: str, ticket_id: str) -> str:
    ref = f"\nTicket Reference: {ticket_id}" if ticket_id else ""
    return (
        f"Dear Customer,\n\n"
        f"Thank you for reaching out to CloudScale AI Support.\n\n"
        f"{response}\n\n"
        f"If you have any further questions, please don't hesitate to reply to this email.\n\n"
        f"Best regards,\n"
        f"CloudScale AI Support Team"
        f"{ref}\n"
        f"This response was generated by our AI assistant. "
        f"For complex issues, you can request human support."
    )


def _format_whatsapp(response: str) -> str:
    if len(response) > _WHATSAPP_MAX:
        response = response[: _WHATSAPP_MAX - 3] + "..."
    return f"{response}\n\n📱 Reply for more help or type *human* for live support."


def _format_web_form(response: str) -> str:
    return f"{response}\n\n---\nNeed more help? Reply to this message or visit our support portal."
